# Generated by Django 4.0.4 on 2022-06-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_address_patient_doctor_patient_alter_product_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playground.people'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playground.people'),
        ),
        migrations.AlterField(
            model_name='product',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.people'),
        ),
    ]
