# Generated by Django 4.0.4 on 2022-06-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_doctor_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='patient',
        ),
    ]
